### ISSUE TITLE
The configuration unit was not in the module as expected

### ISSUE THREAD

**Issue by JohnAZoidberg** [mrlacey/my-config#1]
Hey, I ran into the same issue when trying to run the system configuration to change windows settings.
It seems that the powershell module to do that got updated and changed in an incompatible way.

You can check out the classes here: https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.2.1-alpha/Content/Microsoft.Windows.Developer.psm1
Compare that to: https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.1.3-alpha/Content/Microsoft.Windows.Developer.psm1
They merged a bunch of settings into the same resources with multiple settings.

This is an example that works with the latest version:

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

###########################################################################
# This configuration will enable or disable various Windows Settings.     #
# PowerShell module: Microsoft.Windows.Developer (0.2.1-alpha)            #
###########################################################################

properties:
  resources:
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present
# See https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.2.1-alpha/Content/Microsoft.Windows.Developer.psm1
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Configure Explorer
        allowPrerelease: true
      settings:
        FileExtensions: Show  # Hide
        HiddenFiles: Show # Hide
        ItemCheckBoxes: Show # Hide
#         # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
#         RestartExplorer: true # Required to apply changes
# See https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.2.1-alpha/Content/Microsoft.Windows.Developer.psm1
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Configure Taskbar
        allowPrerelease: true
      settings:
        Alignment: Left  # Middle
        HideLabelsMode: Always # WhenFull, Never
        SearchBoxMode: Hide # ShowIconOnly, SearchBox, ShowIconAndLabel
        TaskViewButton: Show # Hide
        WidgetsButton: Show # Hide
#         # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
#         RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/UserAccessControl
      directives:
        description: Configure UAC prompt
        allowPrerelease: true
      settings:
        AdminConsentPromptBehavior: KeepCurrentValue
          #NoCredOrConsentRequired
          #RequireCredOnSecureDesktop
          #RequireConsentOnSecureDesktop
          #RequireCred
          #RequireConsent
          #RequireConsentForNonWindowsBinaries
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Disable dark mode
        allowPrerelease: true
      settings:
        Ensure: Absent
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
  configurationVersion: 0.2.0
```
