### ISSUE TITLE
VSCode exentions

### ISSUE THREAD

**Issue by Gijsreyn** [mrlacey/my-config#2]
VSCode exentions should now be available with the alpha release of `Microsoft.VSCode.Dsc` PowerShell module:

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.VSCode.Dsc/VSCodeExtension
      id: Grammarly
      directives:
        description: Install Grammarly extension
        allowPrerelease: false
      settings:
        Name: znck.grammarly
  configurationVersion: 0.2.0
```

**Comment by Gijsreyn** [comment]
@mrlacey Interesting to know that this was just released :)

**Comment by mrlacey** [comment]
Sadly, I couldn't get this to work :/

**Comment by Gijsreyn** [comment]
What happened @mrlacey ?

**Comment by mrlacey** [comment]
It just fails with the generic messages:

`"Couldn't apply settings from configuration file"`
and
`"The configuration unit could not be found."`

**Comment by denelon** [comment]
allowPrerelease should be true for DSC v2 modules that aren't released as stable to the PowerShell gallery. The example below ensures VSCode is installed and it will then add the extension.

I just helped someone who was hitting the same error, and they had some different properties in their configuration file than the "latest" version of the resource uses.

```YAML
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-vs-code
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.VSCode.DSC/VSCodeExtension
      id: install-csharp-dev-kit
      dependsOn:
        - install-vs-code
      directives:
        description: Install C# Dev Kit
        allowPrerelease: true
      settings:
        name: ms-dotnettools.csdevkit
        exist: true
```
